### ISSUE TITLE
Add OAuth to Chrome Extension Issue Reporter

### ISSUE THREAD

**Issue by DonovanJump** [BPS-Consulting/wafir#49]
### Description

As a user when I submit an Issue through the chrome extension then I expect the screenshot to be uploaded to the repo.

### Additional Information

See also #84 

### Acceptance Criteria

- [ ] User can set their OAuth credentials
- [ ] OAuth validates successfully
- [ ] Screenshots upload to the repository

### Tasks
- [ ] TODO
